### ISSUE TITLE
MediathekView 3.30+ requires Java 11, dependence on javaruntime installs Java 8.

### ISSUE THREAD

**Issue by kintrupf** [AdmiringWorm/chocolatey-packages#103]
The package MediathekView currently depends on the package javaruntime, which will install a JRE 8. However, as of version MediathekView 3.30, Java 11 is required , so it will not run.
MediathekView 3.30 works with the package AdoptOpenJDK (which installs  a JDK 12), but IMHO a meta package which adds a dependency on *any* Java 11 or higher would be a better solution. 
There is a bug in AdoptOpenJDK11JRE, Mediathek will not work properly with that version.

**Comment by AdmiringWorm** [comment]
Thank you for opening this issue, I plan to look into replacing the dependency of MediaThekView in more detail during the weekend.

> MediathekView 3.30 works with the package AdoptOpenJDK (which installs a JDK 12)

That sounds good, good to know that the dependency can be replaced with AdoptOpenJDK (probably just the OpenJDK package as well). I don't really like that those packages have hard-coded paths though, but I will get over it :smile:.

> but IMHO a meta package which adds a dependency on any Java 11 or higher would be a better solution.

That is of course the optimal solution, but unfortunately not yet possible. It will be possible once the notion of virtual packages is implemented in choco (but then it will take a year or so until we can use it).

> There is a bug in AdoptOpenJDK11JRE, Mediathek will not work properly with that version.

That is good to know, however specifying a minimum version for the would any dependency would probably be in the 11.x range anyhow (or as low as I can get it).
Will do some testing when I start looking at this.

**Comment by AdmiringWorm** [comment]
I have been trying to look into this issue, and so far have been unsuccessful about running mediathekview together with adoptopenjdk.

Sure, I am able to run the `.jar` file itself with adoptopenjdk, but the executable itself is complaining that it is unable to find version 11+ of the jre.

Running the `.jar` file manually is something I really don't want to do, as such I will postpone the issue for now and will look further into it when I get more time available.

**Comment by kintrupf** [comment]
If I recall correctly I needed to add the path to the AdoptOpenJDK in the registry. That's an option that the AdoptOpenJDK installer provides, but which is not used with the choco install of that package.
The key is something like "HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\12" and the value is named "JavaHome" with the path of AdoptOpenJDK .

I'll raise an issue with the AdoptOpenJDK choco maintainer to add that option to their choco installer.

**Comment by AdmiringWorm** [comment]
It would be great if you could open an issue with the maintainer and get him to add the creation of JAVA_HOME (There are complications he would need to consider though for it, have it already been created by a different JDK for instance).

**Comment by AdmiringWorm** [comment]
Small update on the status (just as much as a reminder for myself :smile:).
I will eventually add a dependency on the [AdoptOpenJDKJRE](https://chocolatey.org/packages/AdoptOpenJDKJRE) package when the next 11.x version is released (around 2 weeks according to the comment of @johanjanssen here: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1315#issuecomment-537347644)

**Comment by AdmiringWorm** [comment]
As there never was released a version of the `adoptopenjdkejre` package for 11.x, I have decided to push a new version with as low of a version dependency I could get (version 12.0.0.33).

This will be included in the next package update.

**Comment by johanjanssen** [comment]
There actually is one: adoptopenjdk11jre. Or you could use the latest jre (13 at the moment): adoptopenjdkjre

**Comment by AdmiringWorm** [comment]
@johanjanssen I am aware. I am using the `adoptopenjdkjre` package, only set the dependent version to the lowest. It will install the latest one when a user installs the mediathekview package.

I am not using the `adoptopenjdk11jre` as I don't want to force a user to only use the 11.x range of adoptopenjdk.
But thanks for the suggestion nonetheless.

**Comment by AdmiringWorm** [comment]
@all-contributors please add @kintrupf for bug
