### ISSUE TITLE
(r.project) Installing will try to reuse existing inf file

### ISSUE THREAD

**Issue by scw** [AdmiringWorm/chocolatey-packages#17]
If the `%LOCALAPPDATA%\temp\chocolatey\R.Project.Install.inf` exists from a previous installation or upgrade, installing `r.project` will reuse this file because of [this check](https://github.com/AdmiringWorm/chocolatey-packages/blob/master/automatic/r.project/tools/chocolateyInstall.ps1#L19). In my case, I typically just update R with `cup all` and in the past, this has gotten me the newest version installed into the correct directory. Here, because the 3.4.4 inf file was still in temp, it contained this line:
```
Dir=C:\Program Files\R\R-3.4.4
```
Which installed R 3.5.0 into the Program Files\R-3.4.4 directory on top of the existing R 3.4.4. Perhaps on successful installation this file should be cleaned up? I understand its in temp and may be cleaned up in which case this issue won't be observed, but I think it would be better to be explicit after a successful upgrade. Happy to send on any logs or other details, and thank you for maintaining this package!

**Comment by AdmiringWorm** [comment]
This have now been fixed in the repo, a update have been queued on the build server and should push out a fix version within the next few minutes.

Let me know if you discover any other problems (or if you have any suggestions)
