### ISSUE TITLE
(innosetup) Downloading setup instead of including it into the chocolatey package

### ISSUE THREAD

**Issue by quincunx** [AdmiringWorm/chocolatey-packages#24]
**Is your feature request related to a problem? Please describe.**
The moderation of the chocolatey package takes more time, as it includes the inno setup file (https://github.com/chocolatey/package-validator/wiki/BinariesIncluded).

**Describe the solution you'd like**
Download the setup during installation, e.g. as with DeepGit 

I could prepare a PR for this.

**Comment by AdmiringWorm** [comment]
No, just NO.
Also, that isn't why the moderation takes longer.

Whenever possible (when license allows it, and the binary isn't too large) binaries should be included in the package.
