### ISSUE TITLE
(lilypond) Automatic upgrade to 2.20 fails

### ISSUE THREAD

**Issue by wiggisser** [AdmiringWorm/chocolatey-packages#243]
I have lilypond 2.18.2 installed via chocolatey. Now as version 2.20 is available, I would like to update to this version via

    choco upgrade lilypond

But I get the following error message:

    Previous version of Lilypond found. Please remove the old version.

**To Reproduce**

1. Install lilypond v 2.18.2
2. run `choco upgrade lilypond` 

**Expected behavior**

Either the existing installation should be updated, or the old version should be uninstalled, and the new version should be installed

- OS: Windows 10, (1903 and 1909)
- Chocolatey version: 0.10.15
- Package version: lilypond 2.20

**Chocolatey Install/Uninstall log**
Please provide a link to a gist with the detail install and/or uninstall log from chocolatey.
The file can be found in `%PROGRAMDATA%\chocolatey\logs
[chocolatey.log](https://github.com/AdmiringWorm/chocolatey-packages/files/4941730/chocolatey.log)
[choco.summary.log](https://github.com/AdmiringWorm/chocolatey-packages/files/4941731/choco.summary.log)

`

**Additional context**

**Comment by AdmiringWorm** [comment]
A new package fix has been pushed to chocolatey.org, which uninstalls the program before trying to install a new version (will take a while before it is approved on the website and available through normal consumption).

Thank you for reporting this issue.
