### ISSUE TITLE
(mediathekview) Allow changing the installation path

### ISSUE THREAD

**Issue by debrabant** [AdmiringWorm/chocolatey-packages#25]
It would be great if the MediathekView package for chocolatey could obtain an option to create a link to MediathekView.jar instead of to MediathekView.exe on the Desktop (the reason being that in my environment, starting .exe files from a path like C:\ProgramData\chocolatey\lib\MediathekView\tools\MediathekView-13.2.1 is disabled). Alternatively, also an option to change the installation path would help.

**Comment by AdmiringWorm** [comment]
I can certainly add an option to change the installation path.

Not completely sure about adding a link to the jar file though, but I'll definitely think about it.

**Comment by AdmiringWorm** [comment]
I've updated the issue title (since I'm using the title itself in the changelog of the package

**Comment by AdmiringWorm** [comment]
I've added a change to the package that allows to change the install path, I've also queued a forced update which should be pushed to chocolatey soon

**Comment by debrabant** [comment]
Thank you!
