### ISSUE TITLE
(meld) Create a shim to start meld from command line

### ISSUE THREAD

**Issue by cmorty** [AdmiringWorm/chocolatey-packages#282]
**Is your feature request related to a problem? Please describe.**
It is not possible to run meld from commandline

**Describe the solution you'd like**
Create a shim to `C:\ProgramData\chocolatey\bin\meld`

**Describe alternatives you've considered**
I can create a shim myself or add meld to the `PATH`. Neither is the Chocolatey way.

**Additional context**
I willing to provide a PR, if there is interest and a realistic chance to get merged.

**Comment by AdmiringWorm** [comment]
This is something that's been on my TODO list, but never had the chance to get around to add the feature.

If you are willing to provide a PR to add the necessary directory on `PATH` (and remove it during uninstall), I would really appreciate it.

**Comment by cmorty** [comment]
@AdmiringWorm I was planing on creating a shim - not adding yet another path to PATH. ;-)

**Comment by AdmiringWorm** [comment]
Personally, I think adding it to the `PATH` is more appropriate considering it will by default be installed to `Program Files`.
However, I am not fixed on having it that way, so either way is fine.
Just remember that it will need to support installations that isn't installed to the default directory, and it needs to be removed during uninstalls.

**Comment by AdmiringWorm** [comment]
@cmorty any update on this? Do you still wish to create/open a PR for getting this added?

**Comment by cmorty** [comment]
@AdmiringWorm I kind of got a bit demotivated, after terribly failing with the Sysinternals suite-PR. It seems like I do have some "free" time. So if you're still interested I'll see what I can do.

**Comment by AdmiringWorm** [comment]
> So if you're still interested I'll see what I can do.

Yeah, I am still interested. So feel free to create a PR whenever you got the time.
