### ISSUE TITLE
Install/Uninstall is not Silent, Installer appears

### ISSUE THREAD

**Issue by misilot** [AdmiringWorm/chocolatey-packages#332]
**Describe the bug**
When installing via ```choco install r.project --confirm --params /AddToPath```

**To Reproduce**

1. ```choco install r.project --confirm --params /AddToPath```
2. ```choco uninstall r.project -y```

**Expected behavior**
Should not display any windows during install

**Screenshots**
![image](https://user-images.githubusercontent.com/1446856/130972920-58c9f9a0-a190-48d8-89ae-001561f19277.png)

**Chocolatey Install/Uninstall log**

**Additional context**
Looking at https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Can-I-customize-the-installation_003f, it looks like it might need to be /VERYSILENT instead of /SILENT

**Comment by AdmiringWorm** [comment]
Packages on the community package repository are expected to be unattended, but not necessarily silent.

The installation works as expected as long.
