### ISSUE TITLE
[Meld] Allow to choose/change locale

### ISSUE THREAD

**Issue by maicol07** [AdmiringWorm/chocolatey-packages#345]
**Is your feature request related to a problem? Please describe.**
There is no way to select a UI language. The official installer allows this

**Describe the solution you'd like**
An option when installing Meld to choose UI language

**Comment by AdmiringWorm** [comment]
> There is no way to select a UI language. The official installer allows this

The official installer does not contain such a functionality, maybe it used to but at least in the current installer, there is not a way to select a language.
Also, just in case you aren't aware, the package uses the official installer to do the installation of meld.

Below is a quick installation I did from beginning to end.
![no-locale-select](https://user-images.githubusercontent.com/1474648/144124821-90ca1d99-0450-47bb-9c23-7f6f4a88453a.gif)
.

> An option when installing Meld to choose UI language

Sorry, but there is not much I can do until it is included as part of the software installation.

As this isn't anything I do something about, I will be closing this issue.
