### ISSUE TITLE
Any version of qtcreator package for 32 bit Windows and before version 4.14 for any Windows probably do not work

### ISSUE THREAD

**Issue by lebarsfa** [AdmiringWorm/chocolatey-packages#362]
**Describe the bug**
To my knowledge, `qtcreator` 4.13.3 was the last package version really working for 32 bit Windows (later versions were providing 32 bit files but `qtcreator` was not working). Unfortunately, this package version does not work any more since the links it attempts to download were moved from https://download.qt.io/official_releases/ to https://download.qt.io/archive/ few weeks ago (note that the package is only 1 year old). This is likely to be the same for other previous versions and I guess it will be the same in a few months for more recent package versions (which work only in 64 bit anyway).

**To Reproduce**
Try to install any version of `qtcreator` package on a 32 bit computer, probably none will work.
Try to install any version of `qtcreator` package before version 4.14 on a 64 bit computer, probably none will work.

**Expected behavior**
Since Windows 10 is likely to still be supported for 32 bit computers for some time (2025?), it would be good to publish an updated version of `qtcreator` 4.13.3 (e.g. [qtcreator 4.13.3.20211229](https://www.ensta-bretagne.fr/packages/choco/qtcreator.4.13.3.20211229.nupkg)) with updated links with https://download.qt.io/archive/.
Additionally, to prevent the same issue for recent versions, maybe we could try something like [this](https://github.com/lebarsfa/Packages/blob/66005b3155cd7f209359dae3d4ae58783fe2793b/choco/qtcreator/tools/chocolateyinstall.ps1#L5-L29) :
```powershell
$url      = 'https://download.qt.io/official_releases/qtcreator/4.13/4.13.3/installer_source/windows_x86/qtcreator.7z'
$url64bit = 'https://download.qt.io/official_releases/qtcreator/4.13/4.13.3/installer_source/windows_x64/qtcreator.7z'
try {
  Get-WebHeaders -url $url
} 
catch {
  $url      = 'https://download.qt.io/archive/qtcreator/4.13/4.13.3/installer_source/windows_x86/qtcreator.7z'
}
try {
  Get-WebHeaders -url $url64bit
} 
catch {
  $url64bit = 'https://download.qt.io/archive/qtcreator/4.13/4.13.3/installer_source/windows_x64/qtcreator.7z'
}

$packageArgs = @{
  packageName    = $env:ChocolateyPackageName
  url            = $url
  url64bit       = $url64bit
  destination    = "$installToolsPath\$env:ChocolateyPackageName"
  checksum       = '641f68f2d60ab57d6e3f48c14fd2e1b52338bf11ce5dd5e94fa39adbe6528638'
  checksumType   = 'sha256'
  checksum64     = '189e18125b277a95f5ee28a41193b89a858444025477ff5c28c2986e30b0b438'
  checksumType64 = 'sha256'
}
```

**Desktop:
- OS: Windows 10, especially 32 bit
- Chocolatey version: 0.10.15
- Package version: `qtcreator` before 4.14

**Comment by AdmiringWorm** [comment]
> To my knowledge, qtcreator 4.13.3 was the last package version really working for 32 bit Windows (later versions were providing 32 bit files but qtcreator was not working).

yes, unfortunately, it seems the developers of QT Creator stopped providing valid 32bit archives after that time and it was never detected. Not much I can do about that, unfortunately.

> Since Windows 10 is likely to still be supported for 32 bit computers for some time (2025?), it would be good to publish an updated version of qtcreator 4.13.3 (e.g. [qtcreator 4.13.3.20211229](https://www.ensta-bretagne.fr/packages/choco/qtcreator.4.13.3.20211229.nupkg)) with updated links with [download.qt.io/archive](https://download.qt.io/archive/).

Sorry to disappoint you, but I won't be going back to older versions to update links used in the package. If you really need to install an older version of the package, you should really be considering getting a Pro license for Chocolatey so you can leverage the Chocolatey CDN when a package has non-functioning URLs.
