### ISSUE TITLE
(mediathekview) Add support for 64-bit archive

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [AdmiringWorm/chocolatey-packages#367]
It seems that Choco uses the 32-bit version of MediathekView, both for the program itself and for the installed Java runtime environment.
The MediathekView authors claim that it runs better in the 64-bit version. I had a lengthy discussion on the [MediathekView forum](https://forum.mediathekview.de/topic/4601/mediathekview-startet-nicht-keine-fehlermeldung-prozess-erscheint-nicht/10) about why I use the 32-bit version in the first place.
The authors do also provide a 64-bit version alternatively.
I would recommend switching over. There aren't that many 32-bit systems left anyway, are there?
Even better if it would be possible to install 32 or 64 versions depending on the target system.

**Comment by DaDirnbocher** [comment]
> The MediathekView authors claim that it runs better in the 64-bit version.

A funny description of what is in the [changelog ](https://github.com/mediathekview/MediathekView/blob/develop/CHANGELOG.md) for the upcoming version 13.9.

In short: MV 13.9. will be the last version supporting 32-bit OS.

**Comment by ThomasHeinrichSchmidt** [comment]
Oh. During my [recent discussion](https://forum.mediathekview.de/topic/4601/mediathekview-startet-nicht-keine-fehlermeldung-prozess-erscheint-nicht) nobody mentioned this. So in that case the change is a necessity.

**Comment by AdmiringWorm** [comment]
Mediathekview will be dropped from this repository. See the RFM request: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1455
