### ISSUE TITLE
master-pdf-editor Error - hashes do not match

### ISSUE THREAD

**Issue by taosecurity** [AdmiringWorm/chocolatey-packages#386]
Hello, I'm seeing this checksum error:

You have master-pdf-editor v5.8.63 installed. Version 5.8.70 is available based on your source(s).
Progress: Downloading master-pdf-editor 5.8.70... 100%

master-pdf-editor v5.8.70 [Approved]
master-pdf-editor package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'E630CE1C1BA2F44A334521A373195BA31B55BCAFD84F5D2EBD079D59ABA125D3FD660916B12661986C4B632243602DAFEF89E28C3A89C2CB28F26801801D5AC1'.
Downloading master-pdf-editor
from '[https://code-industry.net/p...](https://disq.us/url?url=https%3A%2F%2Fcode-industry.net%2Fpublic%2FMasterPDFEditor-setup.exe%27%3AwYVvh5dIGU11yR6pND9g6NWiZog&cuid=2163236)
Progress: 100% - Completed download of C:\Users\XX\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe (33.44 MB).
Download of MasterPDFEditor-setup.exe (33.44 MB) completed.
Error - hashes do not match. Actual value was 'E630CE1C1BA2F44A334521A373195BA31B55BCAFD84F5D2EBD079D59ABA125D3FD660916B12661986C4B632243602DAFEF89E28C3A89C2CB28F26801801D5AC1'.
ERROR: Checksum for 'C:\Users\XX\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' did not meet '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of master-pdf-editor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1'.
See log for details.

Thank you.

**Comment by liver121888** [comment]
Have you got it fixed? I was trying to install master-pdf-editor 4.3.89. Met with the same problem.

**Comment by AdmiringWorm** [comment]
I apologise for not seeing this issue before now. The package has been automatically updated since this issue was last updated, and I am getting the same checksum as the package.

As such, I'll get this issue closed, but if the problem continues, please let me know, and I can look into it.
