### ISSUE TITLE
(authy-desktop) Install fails with 403 error from AWS S3

### ISSUE THREAD

**Issue by tjoneseng** [AdmiringWorm/chocolatey-packages#390]
> choco install authy-desktop
Chocolatey v1.2.0
Installing the following packages:
authy-desktop
By installing, you accept licenses for the packages.

authy-desktop v2.2.1 [Approved]
authy-desktop package files install completed. Performing other installation steps.
The package authy-desktop wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Attempt to get headers for https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/2.2.1/win32/x64/Authy%20Desktop%20Setup%202.2.1.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/2.2.1/win32/x64/Authy%20Desktop%20Setup%202.2.1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
Downloading authy-desktop 64 bit
  from 'https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/2.2.1/win32/x64/Authy%20Desktop%20Setup%202.2.1.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://s3.amazonaws.com/authy-electron-repository-production/authy/stable/2.2.1/win32/x64/Authy%20Desktop%20Setup%202.2.1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of authy-desktop was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\authy-desktop\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - authy-desktop (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\authy-desktop\tools\chocolateyinstall.ps1'.
 See log for details.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

**Comment by AdmiringWorm** [comment]
As far as I can see, this is not a problem anymore. This likely happened after the software had updated but before the automatic updater had run (or a new version had yet to be approved on Chocolatey Community Repository).

But as it does not seem to be a problem, I'll close this issue.
