### ISSUE TITLE
(MediathekView) Package is outdated

### ISSUE THREAD

**Issue by forenta** [AdmiringWorm/chocolatey-packages#392]
**Additional context**
Is: 13.9.0
Available: 13.9.1 since July 2022
https://download.mediathekview.de/stabil/

**Describe the bug**
Start the application - it will let you know that the version is outdated

**To Reproduce**

Do a clean start of the package

**Expected behavior**
-

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2451238/229349684-cbed544a-9b72-4070-90f1-b942dc9cb9e5.png)

**Desktop (please complete the following information):**

- OS: Windows 11 x64
- Chocolatey version: 1.3.1
- Package version: ?

**Chocolatey Install/Uninstall log**
Please provide a link to a gist with the detail install and/or uninstall log from chocolatey.
The file can be found in `%PROGRAMDATA%\chocolatey\logs`

**Comment by AdmiringWorm** [comment]
I am not interested in maintaining this package anymore, as such an RFM issue has been created here: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1455
