### ISSUE TITLE
(LilyPond) Package outdated, 2.24.1 is out

### ISSUE THREAD

**Issue by stefan-muc** [AdmiringWorm/chocolatey-packages#398]
**Describe the bug**
Package is outdated, version 2.22.2, but most recent (stable) version is 2.24.1 http://lilypond.org/download.de.html

**Expected behavior**
Package shall install most recent version

**Comment by AdmiringWorm** [comment]
I have no interest in maintaining this package anymore. As such, an RFM request has been opened.

See: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1453

This package will be removed from this repository.
