### ISSUE TITLE
(r.project) add bin directory to PATH

### ISSUE THREAD

**Issue by jayvdb** [AdmiringWorm/chocolatey-packages#70]
R.project doesnt add `bin` directory to PATH.

I am doing the following to find it and add it to the PATH, which should work as a drop in.  However as this package has the version already in the .ps1, it could make the version a variable and skip the find step.

```ps1
function Add-R-to-PATH
{
  # $list = Get-ChildItem -Directory 'C:\Program Files\R' | Out-String
  # Write-Host $list

  Get-ChildItem -Directory 'C:\Program Files\R' | % {
    $R_ROOT = $_.FullName

    Write-Host 'Setting R_ROOT='$R_ROOT

    Set-ItemProperty -path 'HKCU:\Environment' -name 'R_ROOT' -value $R_ROOT

    $R_BIN = ($R_ROOT + '\bin')

    Install-ChocolateyPath -PathToInstall $R_BIN
  }
  if ($R_ROOT) {
    return $R_ROOT
  }
  throw ('R not found in ' + $list)
}
```

Also I am experiencing that newly installed packages are not in the R libs path either, so it might also need to be added to `.Rprofile` -- still investigating that one.

**Comment by jayvdb** [comment]
By default, CRAN isnt set up, so installing a package results in

```
install.packages("formatR")
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
```

The solution on Unix is to do

```
echo 'options(repos=structure(c(CRAN="http://cran.us.r-project.org")))' >> .Rprofile
```

Now to find the Windows version of that...

**Comment by jayvdb** [comment]
The default repo can be added to `$R_ROOT/etc/Rprofile.site` with
```R
local({r <- getOption("repos")
       r["CRAN"] <- "http://cran.r-project.org"
       options(repos=r)})
```

The next problem is the compilers are not setup, resulting in errors.

```
The downloaded binary packages are in
	C:\Users\appveyor\AppData\Local\Temp\RtmpUVsoEq\downloaded_packages
installing the source package 'markdown'
trying URL 'http://cran.us.r-project.org/src/contrib/markdown_1.0.tar.gz'
Content type 'application/x-gzip' length 80843 bytes (78 KB)
==================================================
downloaded 78 KB
Warning in strptime(xx, f, tz = tz) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
* installing *source* package 'markdown' ...
** package 'markdown' successfully unpacked and MD5 sums checked
** using staged installation
** libs
*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c Rbase64.c -o Rbase64.o
/bin/sh: c:/Rtools/mingw_32/bin/gcc: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/i386/Makeconf:208: Rbase64.o] Error 127
ERROR: compilation failed for package 'markdown'
* removing 'C:/Program Files/R/R-3.6.0/library/markdown'
```

**Comment by AdmiringWorm** [comment]
I am not completely sure if this is the responsibility of the package.
Normally, a chocolatey package is just a thin wrapper around the officially provided installer, and the installer itself do not allow the option to add anything to path.

If you could tell me **why** you would want this added to the path, then I may start taking this into consideration.

**Comment by jayvdb** [comment]
Well they start out as thin wrappers, but they usually grow from there.
e.g. the php one does a lot of setup https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/php/tools/chocolateyInstall.ps1

It is definitely expected that choco packages put binaries into the system path, or warn users where they are located.
It is also common for unix-y packages to set FOO_HOME / FOO_ROOT style variables if they are normally set by unix distro packagers, so Windows users have a similar experience.

Why?  I need to use the R package in CI, so I need to build these automated post-install fixes, and I am happy to share them.

**Comment by AdmiringWorm** [comment]
> Well they start out as thin wrappers, but they usually grow from there.

Most both start out and continue as thin wrappers, this is what is usually expected. Especially when it is a package that handles an installer, for packages that handles archives there is usually more worked involved to get the program to a functional state (this is the case of php).

The php package is not really relevant in this case, as most of the work made to the package was needed to get it to a functional state (I would know, as I am 1 of the maintainers that have been working on the package).

> It is definitely expected that choco packages put binaries into the system path, or warn users where they are located.

You got that completely wrong, it is expected to be put on the system path if and only if it is a cli only program (for portable packages), or if the installer supports installing to path by default.

Now, I will admit that I don't know much about R, and how it is expected to be used. By from the looks of it, it is a gui program and meant to be used through a gui.

Now, don't get me wrong. I am not against the idea of implementing the ability to add the `bin` directory to path at all, but I am trying to figure out where this should end up.
Depending on the work needed to get the cli edition to work as expected, it may require an additional package to handle said configuration (only to not bloat the installer package to much).
If there is just a need to add the `bin` directior to path, then I could add the necessary code for that pretty quickly (would probably do it through shims though).

> It is also common for unix-y packages to set FOO_HOME / FOO_ROOT style variables if they are normally set by unix distro packagers, so Windows users have a similar experience.

This is something I have almost never seen in a Windows environment, yes they are common in Linux at least (don't know of OSX), but I have seen maybe a handful of programs installed on windows taking the same approach.

**Comment by jayvdb** [comment]
> Now, I will admit that I don't know much about R, and how it is expected to be used. By from the looks of it, it is a gui program and meant to be used through a gui.

It is a programming language, which has a cli repl, like every other half useful programming language, and has many tools which operate from command line.

As I said, I already am using it on a headless VM, and have the fixes to make it work.

**Comment by AdmiringWorm** [comment]
Adding the bin directory to path will be available in the next version of the R.Project package (not the `r` package as it won't pass along the parameters to its dependency).

**Comment by AdmiringWorm** [comment]
@all-contributors please add @jayvdb to ideas
