### ISSUE TITLE
(dumo) package source link is wrong 

### ISSUE THREAD

**Issue by bcurran3** [AdmiringWorm/chocolatey-packages#72]
Currently at https://github.com/dtgm/chocolatey-packages/tree/master/automatic/dumo/

**Comment by AdmiringWorm** [comment]
Technically the url is correct, as that version was pushed by @dtgm.
It is odd that it was pushed by him though, as both the ketarin file and the package directory have been removed by in his repo.

I'll push out a fix version, as the pushed version is also missing the ahk script to close dumo.

**Comment by bcurran3** [comment]
Gary has access to dtgm's repository. You can ask him to turn off automatic updates.

**Comment by AdmiringWorm** [comment]
> Gary has access to dtgm's repository. You can ask him to turn off automatic updates.
> EDIT: Just re-read your statement - yeah weird that it got pushed by "him."

What I am guessing, is that the ketarin instance he is using on the server is using an outdated list of ketarin xml files, I do not believe @gep13 have access to that server though.

I have removed dtgm as a maintainer, so issues like this won't happen in the future for this package.

**Comment by gep13** [comment]
@AdmiringWorm you are correct, I don’t have access to the server. My understanding was that it would pull the latest version of the repository on each execution, so if the files were removed, it wouldn’t be acted on.

If that isn’t the case, or any work is required here, we need to figure out what.  I thought the process we were following would be enough.
