### ISSUE TITLE
Origin installs into wrong dir by default

### ISSUE THREAD

**Issue by TyPh00nCdr** [AdmiringWorm/chocolatey-packages#81]
64 bit OSes should install to "Program Files", while 32 bit OSes should install to "Program Files (x86)". The `helpers`-script, however, returns the 32 bit directory for 64 bit OSes. 

https://github.com/AdmiringWorm/chocolatey-packages/blob/6d8bbf78ed49c55d3c7b615a019be62a4d3be2ed/automatic/origin/tools/helpers.ps1#L9

I would propose simply comparing against `64` here. That would probably be the simplest fix.

**Comment by AdmiringWorm** [comment]
> 64 bit OSes should install to "Program Files", while 32 bit OSes should install to "Program Files (x86)".

I am sorry, but that is completely wrong.
If you start installing software to `Program Files (x86)` on a 32bit OS, then you are asking for a world of hurt. That folder do not exist on a 32bit OS, and there is no need for it there either.

Let us take a moment and think of where softwares should be installed by default:
- A 64bit software on a 64bit OS should install to `Program Files`
- A 32bit software on a 32bit OS should install to `Program Files`
- A 32bit software on a 64bit OS should install to `Program Files (x86)` (This is also the intent of that folder, as a 32bit software is not considered a true architecture for a 64bit OS).

> The helpers-script, however, returns the 32 bit directory for 64 bit OSes.

Which is correct for the origin software, as the software is a 32bit application.

> I would propose simply comparing against 64 here. That would probably be the simplest fix.

No, just no. Until origin is a 64bit software, the comparison should not change (when/if origin becomes a 64bit software the check is actually no longer needed).
