### ISSUE TITLE
Add chocolatey package for RTools

### ISSUE THREAD

**Issue by jimhester** [AdmiringWorm/chocolatey-packages#99]
The R project has a custom compiler toolchain called [RTools](https://cran.r-project.org/bin/windows/Rtools/) which is distributed separately from the main installer, as it is only needed when compiling R packages that contain C/C++ or FORTRAN code.

It would be useful to have rtools installable via chocolatey. There is an existing install script available at https://github.com/hannesmuehleisen/choco-rtools/blob/master/tools/chocolateyinstall.ps1 to do so, but I am not familiar enough with the layout of this repo or chocolatey packages to submit a full PR myself.

**Comment by AdmiringWorm** [comment]
I'm sorry, but I most likely won't be taking on any new package any time soon.
As such I would suggest opening an issue over at: https://github.com/chocolatey-community/chocolatey-package-requests/issues

That is the where most request for new packages goes (and for new maintainers).

**Comment by AdmiringWorm** [comment]
Or if you want to maintain the package yourself, you can also reach out on [gitter](https://gitter.im/chocolatey/chocolatey.org) asking for help on getting started.
